package: yaafe
user: thomasfillon

platform:
  - linux-64

engine:
  - python=2.7

install:
  - conda config --add channels thomasfillon # libmpg123
  - conda config --add channels hcc  # libsndfile
  - conda config --add channels menpo  # eigen, fftw3
  - conda config --add channels etetoolkit  # argtable2
  - conda config --add channels cyclus  # lapack

script:
  - conda build conda.recipe

build_targets: conda